server.port: 8083

spring:
  application.name: learn-spring-cloud-gateway
  output.ansi.enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producer
          uri: lb://learn-spring-cloud-producer
          predicates:
            - Path=/hello
        - id: consumer
          uri: lb://learn-spring-cloud-consumer
          predicates:
            - Path=/consume, /login
    nacos.discovery:
      server-addr: 127.0.0.1:8848
      namespace: dev
      group: dev